name: "🌟 Feature Request"
description: "Feel free to propose a new feature."
title: "[Feature]: <Name the feature you want to add>"
body:
  - type: textarea
    id: "3"
    attributes:
      label: "Description"
      description: |
        Please provide a clear and concise description of any alternative
        solutions or features you have considered.
    validations:
      required: true
  - type: checkboxes
    id: "1"
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing issues"
          required: true
        - label: "I have read the [Contributing Guidelines](https://github.com/PriyansuMaurya/MedGuide/blob/main/CONTRIBUTING.md)."
          required: true
        - label: "I am willing to work on this issue (optional)"
          required: false
